#define RICE_PATH_MAX 0x1000

#define RICE_ARCHIVE_BLOCK_SIZE_INITIAL 0x100
#define RICE_ARCHIVE_BLOCK_SIZE_MAX 0x10000

#define RICE_ARCHIVE_ENTRY_PACKAGE_INFO "./package-info"
#define RICE_ARCHIVE_ENTRY_PACKAGE_INFO_SIZE (sizeof(RICE_ARCHIVE_ENTRY_PACKAGE_INFO) - 1)

#define RICE_METAINF_SIGNATURE "\31METAINF"
#define RICE_METAINF_SIGNATURE_SIZE (sizeof(RICE_METAINF_SIGNATURE) - 1)
#define RICE_VERSION 1